class_name Narrator
extends RefCounted
## Konferansjer: categorized Polish commentary. The show host watches what you
## do and reports it for the audience. Port of systems/narrator.py say(category)
## — a curated subset of categories the board triggers, with the EXACT Polish
## lines from dungeon_kraulem/ui/locales/pl.json (GENERATED by tools/gen_narrator.py,
## not retyped — re-run that script if the locale changes).

const CATEGORIES: Dictionary = {
	"clever_action": ["Widownia notuje. Sponsor dorzuca premię."],
	"env_kill": ["Loch sam się skarży na ciebie do działu prawnego.", "Kreatywne. Bestialskie. Wysoka oglądalność."],
	"impossible_action": ["To by się ładnie wyświetliło, gdyby się dało zrobić."],
	"salvage_success": ["Rozkładasz to z chłodem osoby, która już dawno przestała być sentymentalna.", "Świat tracił właśnie integralność. Plecak zyskał objętość.", "Cicho, sprawnie, brudno — czyli zgodnie z planem."],
	"salvage_fail": ["Coś pęka nie w tę stronę. Materiał zostaje, godność też mniej więcej.", "Próbujesz, świat nie odpowiada. Czas mija. Ręce bolą."],
	"corpse_loot": ["Ciało nie protestuje. Świadkowie czasami protestują."],
	"furniture_salvage": ["Krzesło wnosi sprzeciw. Krzesło zostaje pokonane.", "Z mebla zostaje to, co dało się unieść.", "Dział nieruchomości złoży skargę. Nie do ciebie. Do nikogo konkretnego."],
	"tech_salvage": ["Panel ustępuje. Schemat ujawnia się. Trochę za późno dla projektanta.", "Płytka drukowana, dwa kondensatory, jedna lekcja BHP — wszystko twoje."],
	"craft_success": ["Działa. Nie pytaj dlaczego. Pytanie zwiększa szansę, że przestanie.", "Coś z niczego. Sponsorzy lubią ten content, choć nigdy się do tego nie przyznają."],
	"craft_fail": ["Materiał stawia opór. Sztuka też. Czas leci."],
	"craft_critical_fail": ["Coś pierdyknęło w środku konstrukcji. Materiał poszedł. Dłoń też prawie."],
	"craft_partial": ["Coś się wytworzyło. Coś się przy tym popsuło. Bilans wciąż na plus.", "Wygląda jak prototyp. Działa jak prototyp. Z prototypami się umiera."],
	"clever_craft": ["Twórcze użycie złomu. Widownia patrzy z uznaniem."],
	"dangerous_craft": ["Składasz coś, czego instrukcja brzmiała: nie składaj tego."],
	"absurd_craft_attempt": ["To, co próbujesz złożyć, nie istnieje w żadnym znanym programie szkoleniowym.", "Algorytm nie rozpoznaje czynności. Algorytm odnotowuje styl."],
	"audience_likes_recycling": ["Widownia lubi recykling. Sponsor głośno udaje, że nie lubi."],
	"audience_disgusted": ["Widownia odwraca głowy. Część dla pozoru. Część zostaje."],
	"audience_rise": ["Ratingi wskakują wyżej. Pasek na górze ekranu mruga.", "Widownia podnosi wzrok. To jeszcze nie owacja, ale coś się klei.", "Kanał notuje wzrost. Sponsor notuje notatkę."],
	"audience_drop": ["Widownia odpływa. Ktoś przełącza kanał na pogodę.", "Zainteresowanie spada. Sponsor już patrzy na zegarek.", "Cisza w eterze. Ratingi siadają, a sponsor siada razem z nimi."],
	"class_offer": ["Syndykat obejrzał twoje nagranie i ma sugestie.", "Algorytm cię już zaklasyfikował. Wybór jest formalnością."],
	"everything_is_material": ["W tym lochu wszystko jest częścią czegoś. Część zaczyna być twoja."],
	"disgusting_but_useful": ["Materiał nadaje się. Nikt nie zapyta, skąd, dopóki sam nie powiesz."],
	"rare_material_found": ["Coś, czego sklepy z lochu nie wystawiają. Twoje. Na razie."],
}

## Random Polish line for a category, or "" if none. rng keeps runs seeded.
static func say(category: String, rng: RandomNumberGenerator) -> String:
	var pool: Array = CATEGORIES.get(category, [])
	if pool.is_empty():
		return ""
	return pool[rng.randi_range(0, pool.size() - 1)]

static func has_category(category: String) -> bool:
	return CATEGORIES.has(category) and not (CATEGORIES[category] as Array).is_empty()
