class_name AchievementsCatalog
extends RefCounted
## DCC-flavored achievement catalog, GENERATED from the Python
## systems/achievements.py by tools/gen_achievements.py (Polish verbatim).
## key -> {name, desc, category, hidden}

const CATALOG: Dictionary = {
	"wszystko_jest_surowcem": {"name": "Wszystko jest surowcem", "desc": "Pierwsza rozbiórka zaliczona. System przekwalifikował twój świat na zasoby. Witaj w gospodarce.", "category": "salvage", "hidden": false},
	"meble_tez_krwawia": {"name": "Meble też krwawią", "desc": "Rozłożyłeś krzesło na czynniki pierwsze. Gdzieś we wszechświecie widz obstawia, ile jeszcze wytrzymasz.", "category": "salvage", "hidden": false},
	"recykling_agresywny": {"name": "Recykling agresywny", "desc": "Pięć obiektów rozebranych. Syndykat dziękuje za obniżenie kosztów utrzymania Lochu.", "category": "salvage", "hidden": false},
	"rozbiorka_zwlok": {"name": "Rozbiórka zwłok", "desc": "Potraktowałeś zwłoki jak skrzynkę z częściami. Połowa widowni wyłączyła. Druga zrobiła głośniej.", "category": "harvest", "hidden": false},
	"technicznie_to_loot": {"name": "Technicznie to loot", "desc": "To był fragment ściany. Teraz jest w twoim plecaku. System klasyfikuje to jako inicjatywę.", "category": "salvage", "hidden": false},
	"kradziez_armatury": {"name": "Kradzież armatury", "desc": "Ukradłeś armaturę z kryjówki. Portier zapamięta. Portierzy zawsze pamiętają.", "category": "theft", "hidden": false},
	"sponsor_nie_pochwala": {"name": "Sponsor nie pochwala", "desc": "Naruszyłeś własność sponsora na wizji. Dział prawny Kanału 7 nadał ci właśnie numer sprawy.", "category": "theft", "hidden": true},
	"rzemieslnik_z_paniki": {"name": "Rzemieślnik z paniki", "desc": "Coś z czegoś zrobiłeś i nie wybuchło. Niski próg, ale widzowie lubią debiuty.", "category": "craft", "hidden": false},
	"przepis_jaki_przepis": {"name": "Przepis, jaki przepis", "desc": "Skleiłeś to bez instrukcji, na czuja. System notuje cię jako kreatywnego lub zdesperowanego.", "category": "craft", "hidden": false},
	"inzynieria_odwagi": {"name": "Inżynieria odwagi", "desc": "Kraftowałeś, kiedy coś próbowało cię zjeść. Ręce drżały, ranking rósł.", "category": "craft", "hidden": true},
	"obrzydliwe_ale_dziala": {"name": "Obrzydliwe, ale działa", "desc": "Użyłeś materiału z czyjegoś wnętrza. Działa. Sponsorzy gastronomiczni zerwali umowę.", "category": "craft", "hidden": true},
	"zlota_raczka_lochu": {"name": "Złota rączka lochu", "desc": "Dziesięć rzeczy zmajstrowanych. Loch przechodzi przez twoje ręce jak taśma produkcyjna.", "category": "craft", "hidden": false},
	"pulapka_z_niczego": {"name": "Pułapka z niczego", "desc": "Pierwsza pułapka rozstawiona. Loch ma teraz drugi cień, a ty masz alibi.", "category": "deploy", "hidden": false},
	"samo_sie_rozstawilo": {"name": "Samo się rozstawiło", "desc": "Pułapka odpaliła w twoich rękach. Widzowie nazwali ten klip klasykiem gatunku.", "category": "deploy", "hidden": true},
	"ekonomia_przetrwania": {"name": "Ekonomia przetrwania", "desc": "Dwadzieścia rozbiórek. Jesteś już bardziej śmietnikiem niż człowiekiem. To komplement.", "category": "salvage", "hidden": false},
	"smiec_wartosciowy": {"name": "Śmieć wartościowy", "desc": "Zrobiłeś coś poważnego z najtańszego złomu. Syndykat udaje, że tego nie widział.", "category": "craft", "hidden": true},
	"pierwsza_krew": {"name": "Pierwsza krew, sezon w toku", "desc": "Pierwszy uczestnik skreślony z listy. Sponsorzy odetchnęli — pasywni zawodnicy nie sprzedają reklam.", "category": "combat", "hidden": false},
	"finiszer_kanalu": {"name": "Finiszer Kanału 7", "desc": "Krytyk na żywej antenie. Kamera 4 złapała detal. Reżyser uronił łzę.", "category": "combat", "hidden": false},
	"rzeznia_kontrolowana": {"name": "Rzeźnia kontrolowana (×50)", "desc": "Pięćdziesiąt ciał. Producent stawia ci drinka. Symboliczny, bo i tak stąd nie wyjdziesz.", "category": "combat", "hidden": false},
	"boss_padl_pierwszy": {"name": "Pierwszy boss pada", "desc": "Pierwszy boss piętra leży. Studio sprzedaje czas reklamowy na twojej krwi.", "category": "combat", "hidden": false},
	"anty_host_warknal": {"name": "Nie tak szybko", "desc": "Spadłeś do 1 HP i wstałeś. Widownia myślała, że to koniec. Ty też.", "category": "survival", "hidden": true},
	"reklama_przerywa_walke": {"name": "Reklama przerywa walkę", "desc": "Pięć rund w defensywie. Tak nudno, że System puścił reklamy. Sponsorzy dziękują.", "category": "combat", "hidden": true},
	"brak_zwlok_brak_problemu": {"name": "Brak zwłok, brak problemu", "desc": "Całe piętro bez jednego trupa. Pacyfizm na arenie śmierci. Widzowie są zdezorientowani.", "category": "stealth", "hidden": true},
	"dno_jeszcze_dalej": {"name": "Dno, jeszcze dalej", "desc": "Drugie zejście po schodach. Loch zaczyna zapamiętywać twój numer startowy.", "category": "floor", "hidden": false},
	"piaty_set": {"name": "Piąty set", "desc": "Piętro 5. Wskaźniki oglądalności drgnęły. Ktoś z innej galaktyki obstawił na ciebie.", "category": "floor", "hidden": false},
	"dziesiate_pietro": {"name": "Dziesiąte piętro", "desc": "Połowa Lochu za tobą. Konferansjer nagrał ci osobny jingiel. To nie znaczy, że cię lubi.", "category": "floor", "hidden": false},
	"finalista_sezonu": {"name": "Finalista sezonu", "desc": "Pokonałeś finał. Dyrektor generalny Kanału 7 chce znać twoje plany. To pytanie retoryczne.", "category": "floor", "hidden": true},
	"pakiet_z_sufitu": {"name": "Pakiet z sufitu", "desc": "Pierwsza paczka spadła z sufitu. Marka cię polubiła. Marki kochają zwycięzców i męczenników.", "category": "sponsor", "hidden": false},
	"markowy_uczestnik": {"name": "Markowy uczestnik", "desc": "Sponsorski przepis odblokowany. Masz teraz logo na rękawie i cenę na głowie.", "category": "sponsor", "hidden": false},
	"widownia_gorzej_bije": {"name": "Widownia gorzej bije", "desc": "Oglądalność przekroczyła 50. Powstają pierwsze memy. Niektóre są nawet miłe.", "category": "audience", "hidden": false},
	"kult_jednostki": {"name": "Kult jednostki", "desc": "Oglądalność 80+. W innym układzie gwiezdnym sprzedają koszulki z twoją twarzą. Działki nie dostaniesz.", "category": "audience", "hidden": false},
	"dzielo_mistrzowskie": {"name": "Dzieło mistrzowskie", "desc": "Krytyczny craft, dzieło mistrzowskie. Twoje ręce wiedzą więcej niż ty.", "category": "craft", "hidden": false},
	"apteka_w_plecaku": {"name": "Apteka w plecaku", "desc": "Pierwsze wzmocnienie nałożone. Twój sprzęt dostał drugie życie. Ty wciąż masz jedno.", "category": "craft", "hidden": false},
	"globtroter": {"name": "Globtroter", "desc": "Pięć biomów w jednym sezonie. Loch jest większy, niż obiecywała reklama. Jak zawsze.", "category": "exploration", "hidden": false},
	"okopowiec": {"name": "Okopowiec", "desc": "Przeszedłeś Frontowe Okopy. Plakat propagandowy nadal nie pamięta twojego imienia.", "category": "exploration", "hidden": false},
	"zoofobia_skonczona": {"name": "Zoofobia skończona", "desc": "Wyszedłeś żywy z Zoo Korporacyjnego. Pawie nigdy ci nie wybaczą.", "category": "exploration", "hidden": false},
	"archiwista": {"name": "Archiwista", "desc": "Skończyłeś piętro w Muzeum Spektakli. Kurator ma teraz dwa palce mniej i jedną historię więcej.", "category": "exploration", "hidden": false},
	"karaoke_killer": {"name": "Zabójca karaoke", "desc": "Skończyłeś piętro w Barze U Skurczybyka. Mikrofon pamięta ciszę po twoim wyjściu.", "category": "exploration", "hidden": false},
	"widzialem_legende": {"name": "Widziałem legendę", "desc": "Legendarny przedmiot w plecaku. Na ostatniej stronie pamiętnika masz już ofertę kupna. Od siebie.", "category": "loot", "hidden": false},
	"cala_paleta": {"name": "Cała paleta", "desc": "W jednym runie po jednym przedmiocie z każdej rzadkości. Kolekcjonerzy płaczą, plecak jęczy.", "category": "loot", "hidden": true},
	"niezwykly_zbieracz": {"name": "Niezwykły zbieracz", "desc": "Trzy epiki w jednym runie. Sponsor pyta o nazwę twojej firmy. Nie masz firmy. Jeszcze.", "category": "loot", "hidden": false},
	"klepacz_minibossow": {"name": "Klepacz minibossów", "desc": "Trzech minibossów na jednym piętrze. Mapa układa się sama, byle dalej od ciebie.", "category": "combat", "hidden": false},
	"czystka_srodowiska": {"name": "Czystka środowiska", "desc": "Zabiłeś środowiskiem. Sponsor klaszcze — nie jego budżet i nie jego sprzątanie.", "category": "combat", "hidden": false},
	"taneczny_krok": {"name": "Taneczny krok", "desc": "Piętro bez wejścia w hazard. Ostrożnie. Nudno. Konferansjer woli inne reportaże.", "category": "exploration", "hidden": true},
	"kompletny_hacker": {"name": "Kompletny hacker", "desc": "Pięć terminali zhakowanych. System cię nie lubi, ale zna już twój login.", "category": "tech", "hidden": false},
	"bez_zbroi_bez_smutku": {"name": "Bez zbroi bez smutku", "desc": "Piętro bez zbroi. Każda blizna ma teraz imię i numer odcinka.", "category": "survival", "hidden": true},
	"nadzwyczajne_oszczednosci": {"name": "Nadzwyczajne oszczędności", "desc": "Piętro bez jednego kredytu. Sponsor nie wie, czy płakać, czy cię pozwać.", "category": "survival", "hidden": false},
	"kazdy_ma_imie": {"name": "Każdy ma imię", "desc": "Wypatroszyłeś każde ciało, które po sobie zostawiłeś. Inspektor sponsorski jest pod wrażeniem. I w szoku.", "category": "harvest", "hidden": false},
}

## Stable display order: catalog order, grouped by category in the UI.
const ORDER: Array = [
	"wszystko_jest_surowcem",
	"meble_tez_krwawia",
	"recykling_agresywny",
	"rozbiorka_zwlok",
	"technicznie_to_loot",
	"kradziez_armatury",
	"sponsor_nie_pochwala",
	"rzemieslnik_z_paniki",
	"przepis_jaki_przepis",
	"inzynieria_odwagi",
	"obrzydliwe_ale_dziala",
	"zlota_raczka_lochu",
	"pulapka_z_niczego",
	"samo_sie_rozstawilo",
	"ekonomia_przetrwania",
	"smiec_wartosciowy",
	"pierwsza_krew",
	"finiszer_kanalu",
	"rzeznia_kontrolowana",
	"boss_padl_pierwszy",
	"anty_host_warknal",
	"reklama_przerywa_walke",
	"brak_zwlok_brak_problemu",
	"dno_jeszcze_dalej",
	"piaty_set",
	"dziesiate_pietro",
	"finalista_sezonu",
	"pakiet_z_sufitu",
	"markowy_uczestnik",
	"widownia_gorzej_bije",
	"kult_jednostki",
	"dzielo_mistrzowskie",
	"apteka_w_plecaku",
	"globtroter",
	"okopowiec",
	"zoofobia_skonczona",
	"archiwista",
	"karaoke_killer",
	"widzialem_legende",
	"cala_paleta",
	"niezwykly_zbieracz",
	"klepacz_minibossow",
	"czystka_srodowiska",
	"taneczny_krok",
	"kompletny_hacker",
	"bez_zbroi_bez_smutku",
	"nadzwyczajne_oszczednosci",
	"kazdy_ma_imie",
]
