class_name AchievementsCatalog
extends RefCounted
## DCC-flavored achievement catalog, GENERATED from the Python
## systems/achievements.py by tools/gen_achievements.py (Polish verbatim).
## key -> {name, desc, category, hidden}

const CATALOG: Dictionary = {
	"wszystko_jest_surowcem": {"name": "Wszystko jest surowcem", "desc": "Pierwsza udana rozbiórka. Świat zaczyna wyglądać jak lista materiałów.", "category": "salvage", "hidden": false},
	"meble_tez_krwawia": {"name": "Meble też krwawią", "desc": "Rozebrałeś coś, co miało służyć do siedzenia. Krzesło wnosi sprzeciw.", "category": "salvage", "hidden": false},
	"recykling_agresywny": {"name": "Recykling agresywny", "desc": "Pięć obiektów rozłożonych na części. Loch staje się tańszy.", "category": "salvage", "hidden": false},
	"rozbiorka_zwlok": {"name": "Rozbiórka zwłok", "desc": "Pierwsze ciało potraktowane jak skład części. Widownia patrzy w dwie strony.", "category": "harvest", "hidden": false},
	"technicznie_to_loot": {"name": "Technicznie to loot", "desc": "Coś, co miało być częścią ściany, jest teraz w plecaku.", "category": "salvage", "hidden": false},
	"kradziez_armatury": {"name": "Kradzież armatury", "desc": "Rozebrałeś coś, co należało do toalety w kryjówce. Nikt ci tego nie zapomni.", "category": "theft", "hidden": false},
	"sponsor_nie_pochwala": {"name": "Sponsor nie pochwala", "desc": "Naruszyłeś własność sponsora. W przyszłym briefingu pojawi się twoje nazwisko.", "category": "theft", "hidden": true},
	"rzemieslnik_z_paniki": {"name": "Rzemieślnik z paniki", "desc": "Pierwsze udane wytworzenie czegokolwiek. Palce ci jeszcze pamiętają.", "category": "craft", "hidden": false},
	"przepis_jaki_przepis": {"name": "Przepis, jaki przepis", "desc": "Pierwsze udane improwizowane wytworzenie z samych tagów. Bez instrukcji.", "category": "craft", "hidden": false},
	"inzynieria_odwagi": {"name": "Inżynieria odwagi", "desc": "Skraftowałeś coś podczas zagrożenia. Ręce drgały. Wyszło.", "category": "craft", "hidden": true},
	"obrzydliwe_ale_dziala": {"name": "Obrzydliwe, ale działa", "desc": "Crafting z materiału organicznego z ciała. Działa. Lepiej o tym nie mówić.", "category": "craft", "hidden": true},
	"zlota_raczka_lochu": {"name": "Złota rączka lochu", "desc": "Dziesięć skraftowanych rzeczy. Loch przewija się przez twoje ręce.", "category": "craft", "hidden": false},
	"pulapka_z_niczego": {"name": "Pułapka z niczego", "desc": "Pierwsza rozstawiona pułapka. Loch ma teraz drugi cień.", "category": "deploy", "hidden": false},
	"samo_sie_rozstawilo": {"name": "Samo się rozstawiło", "desc": "Pułapka odpaliła ci w rękach. To też jest treść.", "category": "deploy", "hidden": true},
	"ekonomia_przetrwania": {"name": "Ekonomia przetrwania", "desc": "Dwadzieścia akcji odzysku. Każdy złom liczy się raz.", "category": "salvage", "hidden": false},
	"smiec_wartosciowy": {"name": "Śmieć wartościowy", "desc": "Użyłeś najtańszego materiału w poważnej akcji. Loch nie zauważył tej różnicy.", "category": "craft", "hidden": true},
	"pierwsza_krew": {"name": "Pierwsza krew, sezon w toku", "desc": "Pierwszy zabity uczestnik. Sponsorzy odetchnęli z ulgą.", "category": "combat", "hidden": false},
	"finiszer_kanalu": {"name": "Finiszer Kanału 7", "desc": "Krytyczne trafienie na publicznym ujęciu. Kamera 4 łapie szczegół.", "category": "combat", "hidden": false},
	"rzeznia_kontrolowana": {"name": "Rzeźnia kontrolowana (×50)", "desc": "Pięćdziesiąt zabitych. Producent kupuje ci drinka — symbolicznie.", "category": "combat", "hidden": false},
	"boss_padl_pierwszy": {"name": "Pierwszy boss pada", "desc": "Pokonałeś pierwszego bossa piętra. Studio kupuje czas reklamowy.", "category": "combat", "hidden": false},
	"anty_host_warknal": {"name": "Nie tak szybko", "desc": "Last-stand: pierwszy raz spadłeś do 1 HP i wstałeś. Tylko raz.", "category": "survival", "hidden": true},
	"reklama_przerywa_walke": {"name": "Reklama przerywa walkę", "desc": "Wszedłeś w stan defensywny pięć rund pod rząd. Studio musi puścić reklamy.", "category": "combat", "hidden": true},
	"brak_zwlok_brak_problemu": {"name": "Brak zwłok, brak problemu", "desc": "Pierwsze piętro przeszedłeś bez zabicia nikogo. Sponsorzy pamiętają.", "category": "stealth", "hidden": true},
	"dno_jeszcze_dalej": {"name": "Dno, jeszcze dalej", "desc": "Schody w dół drugi raz. Loch zaczyna pamiętać twoje imię.", "category": "floor", "hidden": false},
	"piaty_set": {"name": "Piąty set", "desc": "Dotarłeś na piętro 5. Sezon się rozkręca.", "category": "floor", "hidden": false},
	"dziesiate_pietro": {"name": "Dziesiąte piętro", "desc": "Połowa Lochu za tobą. Konferansjer przeznaczył ci osobny intro.", "category": "floor", "hidden": false},
	"finalista_sezonu": {"name": "Finalista sezonu", "desc": "Pokonałeś Prezesa Syndykatu. Generalny dyrektor pyta o twoje plany.", "category": "floor", "hidden": true},
	"pakiet_z_sufitu": {"name": "Pakiet z sufitu", "desc": "Otwarłeś pierwszy pakiet sponsorski w pokoju. Marka cię polubiła.", "category": "sponsor", "hidden": false},
	"markowy_uczestnik": {"name": "Markowy uczestnik", "desc": "Odblokowałeś sponsorski przepis. Logo na rękawie.", "category": "sponsor", "hidden": false},
	"widownia_gorzej_bije": {"name": "Widownia gorzej bije", "desc": "Wskaźnik widowni przekroczył 50. Ktoś robi ci memy.", "category": "audience", "hidden": false},
	"kult_jednostki": {"name": "Kult jednostki", "desc": "Wskaźnik widowni przekroczył 80. Ktoś sprzedaje t-shirty.", "category": "audience", "hidden": false},
	"dzielo_mistrzowskie": {"name": "Dzieło mistrzowskie", "desc": "Wytworzyłeś przedmiot mistrzowskiej jakości. Twoje ręce już wiedzą.", "category": "craft", "hidden": false},
	"apteka_w_plecaku": {"name": "Apteka w plecaku", "desc": "Pierwsza nałożona warstwa wzmocnienia. Twoja broń ma teraz drugie życie.", "category": "craft", "hidden": false},
	"globtroter": {"name": "Globtroter", "desc": "Pięć różnych biomów w jednym sezonie. Loch jest większy niż mówią w reklamie.", "category": "exploration", "hidden": false},
	"okopowiec": {"name": "Okopowiec", "desc": "Skończyłeś piętro we Frontowych Okopach. Plakat propagandowy nadal nie pamięta twojego imienia.", "category": "exploration", "hidden": false},
	"zoofobia_skonczona": {"name": "Zoofobia skończona", "desc": "Wyszedłeś żywy z Zoo Korporacyjnego. Pawi nigdy ci nie zapomną.", "category": "exploration", "hidden": false},
	"archiwista": {"name": "Archiwista", "desc": "Skończyłeś piętro w Muzeum Spektakli. Kurator ma teraz dwa palce mniej.", "category": "exploration", "hidden": false},
	"karaoke_killer": {"name": "Zabójca karaoke", "desc": "Skończyłeś piętro w Barze U Skurczybyka. Mikrofon pamięta ciszę po twoim wyjściu.", "category": "exploration", "hidden": false},
	"widzialem_legende": {"name": "Widziałem legendę", "desc": "Pierwszy legendarny przedmiot w plecaku. Kontrakt na sprzedaż jest na ostatniej stronie pamiętnika.", "category": "loot", "hidden": false},
	"cala_paleta": {"name": "Cała paleta", "desc": "W jednym runie miałeś jednocześnie przedmiot z każdej klasy rzadkości. Plecak waży jak twoja przyszłość.", "category": "loot", "hidden": true},
	"niezwykly_zbieracz": {"name": "Niezwykły zbieracz", "desc": "Trzy przedmioty epickie w jednym runie. Sponsor pyta o nazwę firmy.", "category": "loot", "hidden": false},
	"klepacz_minibossow": {"name": "Klepacz minibossów", "desc": "Trzech minibossów w jednym piętrze. Mapa już sama się składa.", "category": "combat", "hidden": false},
	"czystka_srodowiska": {"name": "Czystka środowiska", "desc": "Zabiłeś coś używając hazardu. Sponsor klaszcze — nie jego budżet, nie jego problem.", "category": "combat", "hidden": false},
	"taneczny_krok": {"name": "Taneczny krok", "desc": "Cale piętro bez wejścia w hazard. Konferansjer woli inne reportaże.", "category": "exploration", "hidden": true},
	"kompletny_hacker": {"name": "Kompletny hacker", "desc": "Pięć terminali zhakowanych w jednym sezonie. System cię nie lubi, ale zna.", "category": "tech", "hidden": false},
	"bez_zbroi_bez_smutku": {"name": "Bez zbroi bez smutku", "desc": "Skończyłeś piętro bez założonej zbroi. Twoje blizny mają imiona.", "category": "survival", "hidden": true},
	"nadzwyczajne_oszczednosci": {"name": "Nadzwyczajne oszczędności", "desc": "Skończyłeś piętro nie wydając ani jednego kredytu. Sponsor nie wie czy płakać czy się złościć.", "category": "survival", "hidden": false},
	"kazdy_ma_imie": {"name": "Każdy ma imię", "desc": "Wypatroszyłeś każde ciało które po sobie zostawiłeś przez całe piętro. Inspektor sponsorski jest pod wrażeniem (lub w szoku).", "category": "harvest", "hidden": false},
}

## Stable display order: catalog order, grouped by category in the UI.
const ORDER: Array = [
	"wszystko_jest_surowcem",
	"meble_tez_krwawia",
	"recykling_agresywny",
	"rozbiorka_zwlok",
	"technicznie_to_loot",
	"kradziez_armatury",
	"sponsor_nie_pochwala",
	"rzemieslnik_z_paniki",
	"przepis_jaki_przepis",
	"inzynieria_odwagi",
	"obrzydliwe_ale_dziala",
	"zlota_raczka_lochu",
	"pulapka_z_niczego",
	"samo_sie_rozstawilo",
	"ekonomia_przetrwania",
	"smiec_wartosciowy",
	"pierwsza_krew",
	"finiszer_kanalu",
	"rzeznia_kontrolowana",
	"boss_padl_pierwszy",
	"anty_host_warknal",
	"reklama_przerywa_walke",
	"brak_zwlok_brak_problemu",
	"dno_jeszcze_dalej",
	"piaty_set",
	"dziesiate_pietro",
	"finalista_sezonu",
	"pakiet_z_sufitu",
	"markowy_uczestnik",
	"widownia_gorzej_bije",
	"kult_jednostki",
	"dzielo_mistrzowskie",
	"apteka_w_plecaku",
	"globtroter",
	"okopowiec",
	"zoofobia_skonczona",
	"archiwista",
	"karaoke_killer",
	"widzialem_legende",
	"cala_paleta",
	"niezwykly_zbieracz",
	"klepacz_minibossow",
	"czystka_srodowiska",
	"taneczny_krok",
	"kompletny_hacker",
	"bez_zbroi_bez_smutku",
	"nadzwyczajne_oszczednosci",
	"kazdy_ma_imie",
]
