class_name Meta
extends RefCounted
## Meta-progression: a run end can UNLOCK options for future runs. Port of
## engine/meta_progression.py — the board-evaluable subset of UNLOCK_CATALOG
## (labels verbatim, eval closures ported as a condition spec). Persisted to
## user://meta.json across runs. GENERATED by tools/gen_meta.py.

const SAVE_PATH := "user://meta.json"

## key -> {label, kind, cond, arg}
const UNLOCK_CATALOG: Dictionary = {
	"origin_drugi_cykl": {"label": "Drugi cykl", "kind": "origin", "cond": "run_finished", "arg": 0},
	"species_mutant_chemiczny": {"label": "Mutant chemiczny", "kind": "species", "cond": "floor", "arg": 12},
	"species_ferromanta_meta": {"label": "Ferromanta (start)", "kind": "species", "cond": "floor", "arg": 15},
	"origin_byly_konferansjer": {"label": "Były Konferansjer", "kind": "origin", "cond": "floor", "arg": 17},
	"biome_tunel_karnawalowy": {"label": "Tunel Karnawałowy", "kind": "biome", "cond": "audience_peak", "arg": 60},
	"origin_zhanbiony_showman": {"label": "Zhańbiony Showman", "kind": "origin", "cond": "audience_peak", "arg": 70},
	"origin_dziedzic_k7": {"label": "Dziedzic Kanału 7", "kind": "origin", "cond": "audience_peak", "arg": 120},
	"origin_sponsorowany": {"label": "Sponsorowany Uczestnik", "kind": "origin", "cond": "sponsor_max", "arg": 10},
	"perk_lapowka_dla_portiera": {"label": "Łapówka dla portiera", "kind": "perk", "cond": "sponsor_max", "arg": 20},
	"origin_sponsor_reject": {"label": "Niechciane Dziecko Sponsorów", "kind": "origin", "cond": "sponsor_min", "arg": -5},
	"origin_wieczny_stazysta": {"label": "Wieczny Stażysta", "kind": "origin", "cond": "total_runs", "arg": 3},
	"biome_siec_kanalizacyjna": {"label": "Sieć Kanalizacyjna", "kind": "biome", "cond": "total_runs", "arg": 3},
	"item_skarpetka_pulkownika": {"label": "Skarpetka Pułkownika Recyklingu", "kind": "item", "cond": "total_runs", "arg": 5},
	"perk_insiderskie_info": {"label": "Insiderskie info", "kind": "perk", "cond": "total_runs", "arg": 5},
	"species_bez_twarzy": {"label": "Bez Twarzy", "kind": "species", "cond": "total_runs", "arg": 5},
	"biome_oboz_goblinski": {"label": "Obóz Gobliński", "kind": "biome", "cond": "total_victories", "arg": 1},
	"species_stary_uczestnik": {"label": "Stary Uczestnik", "kind": "species", "cond": "total_victories", "arg": 3},
	"perk_stara_legitymacja": {"label": "Stara legitymacja Syndykatu", "kind": "perk", "cond": "total_victories", "arg": 3},
	"item_mosiezny_pierscien_producenta": {"label": "Mosiężny Pierścień Producenta", "kind": "item", "cond": "zero_kills", "arg": 0},
	"biome_elfia_kolonia": {"label": "Elfia Kolonia", "kind": "biome", "cond": "victory_class", "arg": "occultist"},
}

# ── Persistence ──────────────────────────────────────────────────────────────

static func load_state() -> Dictionary:
	var st := {"unlocks": [], "total_runs": 0, "victories": 0}
	if FileAccess.file_exists(SAVE_PATH):
		var f := FileAccess.open(SAVE_PATH, FileAccess.READ)
		if f != null:
			var parsed: Variant = JSON.parse_string(f.get_as_text())
			if parsed is Dictionary:
				st["unlocks"] = (parsed.get("unlocks", []) as Array).duplicate()
				st["total_runs"] = int(parsed.get("total_runs", 0))
				st["victories"] = int(parsed.get("victories", 0))
	return st

static func save_state(st: Dictionary) -> void:
	var f := FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if f != null:
		f.store_string(JSON.stringify(st))

# ── Evaluation ───────────────────────────────────────────────────────────────

## Did this unlock's condition pass, given the run summary + the post-run totals?
static func _passes(cond: String, arg, summary: Dictionary,
		total_runs: int, total_victories: int) -> bool:
	var sp_max := -999; var sp_min := 999
	for sp in summary.get("top_sponsors", []):
		sp_max = maxi(sp_max, int(sp["attention"]))
		sp_min = mini(sp_min, int(sp["attention"]))
	match cond:
		"run_finished":    return true
		"victory":         return bool(summary.get("victory", false))
		"floor":           return int(summary.get("floor_reached", 0)) >= int(arg)
		"audience_peak":   return int(summary.get("audience_peak", 0)) >= int(arg)
		"sponsor_max":     return sp_max >= int(arg)
		"sponsor_min":     return sp_min <= int(arg)
		"total_runs":      return total_runs >= int(arg)
		"total_victories": return total_victories >= int(arg)
		"zero_kills":      return int(summary.get("kills", 1)) == 0
		"victory_class":   return bool(summary.get("victory", false)) and summary.get("class_key", "") == arg
	return false

## Evaluate the run, persist new unlocks + updated totals, and return the list
## of newly-unlocked Polish labels (for the run-summary screen).
static func record_run(summary: Dictionary) -> Array:
	var st := load_state()
	var total_runs := int(st["total_runs"]) + 1
	var total_victories := int(st["victories"]) + (1 if summary.get("victory", false) else 0)
	var already: Array = st["unlocks"]
	var new_labels: Array = []
	for key in UNLOCK_CATALOG:
		if key in already:
			continue
		var entry: Dictionary = UNLOCK_CATALOG[key]
		if _passes(entry["cond"], entry["arg"], summary, total_runs, total_victories):
			already.append(key)
			new_labels.append(entry["label"])
	st["total_runs"] = total_runs
	st["victories"] = total_victories
	st["unlocks"] = already
	save_state(st)
	return new_labels

static func unlocked_count() -> int:
	return (load_state()["unlocks"] as Array).size()
