class_name RunSummary
extends RefCounted
## End-of-run recap. build() snapshots the run's tallies; render_lines() turns
## them into the Polish results screen. Flavor lines copied verbatim from
## engine/run_summary.py (GENERATED by tools/gen_runsummary.py).

const ANTI_HOST_DEATH_LINES: Array = [
	"Konferansjer pochyla się do mikrofonu: „I to by było na tyle.”",
	"Widownia milknie na pół sekundy. Potem klaszcze.",
	"Kamera 4 łapie ostatnie ujęcie. Reklama za trzy, dwa…",
	"Konferansjer: „Sponsorzy nie zwrócą pieniędzy.”",
	"Z głośników leci jingiel końca odcinka. Smaczny.",
	"Konferansjer wzdycha: „Liczyliśmy na dłużej. No cóż.”",
	"Tłum w studio krzyczy: „JESZCZE RAZ!” — to nie tak działa.",
	"Operator kamery prosi o cięcie. Producent mówi: „nie, tak zostaje.”",
]

const DEATH_LOG_LINES: Array = [
	"Ostatnia myśl: „nie tak to miało wyglądać”. Klasyka gatunku.",
	"Obraz się urywa. Dalej już tylko szum.",
]

## Snapshot the run. `floor` is the Floor sim-state; `victory` true if you
## reached the stairs out. `new_unlocks` is filled in by the caller (Meta).
static func build(floor, victory: bool, rng: RandomNumberGenerator) -> Dictionary:
	var p = floor.player
	var sponsors_top: Array = []
	if floor.sponsors != null:
		for skey in floor.sponsors.top_ranked(3):
			var sd = floor.sponsors.get_sponsor(skey)
			sponsors_top.append({
				"name": sd.get("name_fallback", skey),
				"attention": floor.sponsors.get_attention(skey),
				"mood": floor.sponsors.mood(skey),
			})
	var anti := ""
	if not ANTI_HOST_DEATH_LINES.is_empty():
		anti = ANTI_HOST_DEATH_LINES[rng.randi_range(0, ANTI_HOST_DEATH_LINES.size() - 1)]
	var death := ""
	if not DEATH_LOG_LINES.is_empty():
		death = DEATH_LOG_LINES[rng.randi_range(0, DEATH_LOG_LINES.size() - 1)]
	var zlom := int(floor.inv.get("złom", 0))
	return {
		"victory": victory,
		"floor_reached": floor.depth,                 # the real depth (was room index)
		"turns": floor.turn,
		"kills": p.run_kills,
		"salvaged": p.run_corpses_salvaged,
		"audience_peak": floor.audience.peak if floor.audience != null else 0,
		"audience_final": floor.audience.rating if floor.audience != null else 0,
		"class_key": p.class_key,
		"hp": p.hp, "hp_max": p.max_hp,
		"top_sponsors": sponsors_top,
		"anti_host_line": anti,
		"death_log_line": death,
		"titles": Titles.earned(p, floor, victory, zlom),
		"highlights": Highlights.top(p.flags.get("highlight_reel", []), 3),
		"new_unlocks": [],
	}

## Build the Polish results screen as a list of text lines.
static func render_lines(s: Dictionary) -> Array:
	var out: Array = []
	if s["class_key"] != "":
		out.append("Klasa: %s" % Classes.name_of(s["class_key"]))
	if s["victory"]:
		out.append("FINAŁ ODCINKA. Wychodzisz po schodach. Producent płacze ze szczęścia.")
		out.append("Konferansjer: „No proszę. Następny będzie cięższy.”")
	else:
		if s["anti_host_line"] != "":
			out.append(s["anti_host_line"])
		if s["death_log_line"] != "":
			out.append(s["death_log_line"])
	out.append("")
	out.append("Piętro:            %d" % s["floor_reached"])
	out.append("Tury w lochu:      %d" % s["turns"])
	out.append("Zabójstwa:         %d" % s["kills"])
	out.append("Rozebrane na złom: %d" % s["salvaged"])
	out.append("Widownia (szczyt): %d" % s["audience_peak"])
	out.append("Widownia (koniec): %d" % s["audience_final"])
	if not s["top_sponsors"].is_empty():
		out.append("")
		out.append("Sponsorzy:")
		for sp in s["top_sponsors"]:
			var sign := "+" if int(sp["attention"]) >= 0 else ""
			out.append("  %s  %s%d (%s)" % [sp["name"], sign, int(sp["attention"]), sp["mood"]])
	var titles: Array = s.get("titles", [])
	if not titles.is_empty():
		out.append("")
		out.append("Tytuły tego sezonu:")
		for t in titles:
			out.append("  ★ %s — %s" % [t["label"], t["desc"]])
	var highlights: Array = s.get("highlights", [])
	if not highlights.is_empty():
		out.append("")
		out.append("Highlight Reel:")
		for h in highlights:
			out.append("  ▸ %s" % h)
	if not s["new_unlocks"].is_empty():
		out.append("")
		out.append("Sezon otwiera nowe opcje:")
		for u in s["new_unlocks"]:
			out.append("  + %s" % u)
	return out
