"""Generate godot/sim/narrator.gd from the Python locale's narrator_* lines.
Faithful: the exact Polish strings are copied, not retyped. Re-run if locale edits.
"""
import json, re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCALE = os.path.join(ROOT, "pygame", "dungeon_kraulem", "ui", "locales", "pl.json")
OUT = os.path.join(ROOT, "godot", "sim", "narrator.gd")

# Categories the board demo actually triggers (combat, salvage, crafting,
# audience, class offer). Memetics/dialogue/trap categories come in Phase 6.
WANT = [
    "crit_success", "clever_action", "env_kill", "impossible_action",
    "salvage_success", "salvage_fail", "corpse_loot", "furniture_salvage", "tech_salvage",
    "craft_success", "craft_fail", "craft_critical_fail", "craft_partial", "clever_craft",
    "dangerous_craft", "absurd_craft_attempt", "audience_likes_recycling", "audience_disgusted",
    "audience_rise", "audience_drop", "class_offer", "everything_is_material",
    "disgusting_but_useful", "rare_material_found",
]


def main():
    d = json.load(open(LOCALE, encoding="utf-8"))
    cats = {}
    for k, v in d.items():
        m = re.match(r"narrator_(.+?)_(\d+)$", k)
        if m:
            cats.setdefault(m.group(1), []).append(v)

    def esc(s):
        return s.replace("\\", "\\\\").replace('"', '\\"')

    L = []
    L.append("class_name Narrator")
    L.append("extends RefCounted")
    L.append("## Konferansjer: categorized Polish commentary. The show host watches what you")
    L.append("## do and reports it for the audience. Port of systems/narrator.py say(category)")
    L.append("## — a curated subset of categories the board triggers, with the EXACT Polish")
    L.append("## lines from dungeon_kraulem/ui/locales/pl.json (GENERATED by tools/gen_narrator.py,")
    L.append("## not retyped — re-run that script if the locale changes).")
    L.append("")
    L.append("const CATEGORIES: Dictionary = {")
    n = 0
    for c in WANT:
        if c not in cats:
            continue
        n += 1
        arr = ", ".join('"%s"' % esc(x) for x in cats[c])
        L.append('\t"%s": [%s],' % (c, arr))
    L.append("}")
    L.append("")
    L.append("## Random Polish line for a category, or \"\" if none. rng keeps runs seeded.")
    L.append("static func say(category: String, rng: RandomNumberGenerator) -> String:")
    L.append("\tvar pool: Array = CATEGORIES.get(category, [])")
    L.append("\tif pool.is_empty():")
    L.append("\t\treturn \"\"")
    L.append("\treturn pool[rng.randi_range(0, pool.size() - 1)]")
    L.append("")
    L.append("static func has_category(category: String) -> bool:")
    L.append("\treturn CATEGORIES.has(category) and not (CATEGORIES[category] as Array).is_empty()")
    L.append("")

    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("wrote %s with %d categories" % (OUT, n))


if __name__ == "__main__":
    main()
