"""Generate godot/sim/meta.gd. Ports the UNLOCK_CATALOG subset whose conditions
are evaluable from board run-state (floor reached, audience peak, sponsor
attention, totals across runs, pacifist, victory+class). Labels are copied
verbatim from engine/meta_progression.py; the eval closures are ported as a
small condition spec interpreted by evaluate(). Re-run if labels change.
"""
import re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "pygame", "dungeon_kraulem", "engine", "meta_progression.py")
OUT = os.path.join(ROOT, "godot", "sim", "meta.gd")

# key -> (kind, cond_type, arg).  cond_type interpreted by Meta.evaluate().
#   floor:N audience_peak:N sponsor_max:N sponsor_min:N total_runs:N
#   total_victories:N zero_kills victory victory_class:occultist run_finished
WANT = {
    "origin_drugi_cykl":                ("origin",  "run_finished", 0),
    "species_mutant_chemiczny":         ("species", "floor", 12),
    "species_ferromanta_meta":          ("species", "floor", 15),
    "origin_byly_konferansjer":         ("origin",  "floor", 17),
    "biome_tunel_karnawalowy":          ("biome",   "audience_peak", 60),
    "origin_zhanbiony_showman":         ("origin",  "audience_peak", 70),
    "origin_dziedzic_k7":               ("origin",  "audience_peak", 120),
    "origin_sponsorowany":              ("origin",  "sponsor_max", 10),
    "perk_lapowka_dla_portiera":        ("perk",    "sponsor_max", 20),
    "origin_sponsor_reject":            ("origin",  "sponsor_min", -5),
    "origin_wieczny_stazysta":          ("origin",  "total_runs", 3),
    "biome_siec_kanalizacyjna":         ("biome",   "total_runs", 3),
    "item_skarpetka_pulkownika":        ("item",    "total_runs", 5),
    "perk_insiderskie_info":            ("perk",    "total_runs", 5),
    "species_bez_twarzy":               ("species", "total_runs", 5),
    "biome_oboz_goblinski":             ("biome",   "total_victories", 1),
    "species_stary_uczestnik":          ("species", "total_victories", 3),
    "perk_stara_legitymacja":           ("perk",    "total_victories", 3),
    "item_mosiezny_pierscien_producenta": ("item",  "zero_kills", 0),
    "biome_elfia_kolonia":              ("biome",   "victory_class", "occultist"),
}


def main():
    src = open(SRC, encoding="utf-8").read()
    labels = {}
    for m in re.finditer(r'key\s*=\s*"([^"]+)".*?label_pl\s*=\s*"([^"]+)"', src, re.S):
        labels[m.group(1)] = m.group(2)

    def esc(s):
        return s.replace("\\", "\\\\").replace('"', '\\"')

    L = []
    L.append("class_name Meta")
    L.append("extends RefCounted")
    L.append("## Meta-progression: a run end can UNLOCK options for future runs. Port of")
    L.append("## engine/meta_progression.py — the board-evaluable subset of UNLOCK_CATALOG")
    L.append("## (labels verbatim, eval closures ported as a condition spec). Persisted to")
    L.append("## user://meta.json across runs. GENERATED by tools/gen_meta.py.")
    L.append("")
    L.append('const SAVE_PATH := "user://meta.json"')
    L.append("")
    L.append("## key -> {label, kind, cond, arg}")
    L.append("const UNLOCK_CATALOG: Dictionary = {")
    for key, (kind, cond, arg) in WANT.items():
        lab = labels.get(key, key)
        if isinstance(arg, str):
            argrepr = '"%s"' % esc(arg)
        else:
            argrepr = str(arg)
        L.append('\t"%s": {"label": "%s", "kind": "%s", "cond": "%s", "arg": %s},'
                  % (key, esc(lab), kind, cond, argrepr))
    L.append("}")
    L.append("")
    L.append("# ── Persistence ──────────────────────────────────────────────────────────────")
    L.append("")
    L.append("static func load_state() -> Dictionary:")
    L.append("\tvar st := {\"unlocks\": [], \"total_runs\": 0, \"victories\": 0}")
    L.append("\tif FileAccess.file_exists(SAVE_PATH):")
    L.append("\t\tvar f := FileAccess.open(SAVE_PATH, FileAccess.READ)")
    L.append("\t\tif f != null:")
    L.append("\t\t\tvar parsed: Variant = JSON.parse_string(f.get_as_text())")
    L.append("\t\t\tif parsed is Dictionary:")
    L.append('\t\t\t\tst["unlocks"] = (parsed.get("unlocks", []) as Array).duplicate()')
    L.append('\t\t\t\tst["total_runs"] = int(parsed.get("total_runs", 0))')
    L.append('\t\t\t\tst["victories"] = int(parsed.get("victories", 0))')
    L.append("\treturn st")
    L.append("")
    L.append("static func save_state(st: Dictionary) -> void:")
    L.append("\tvar f := FileAccess.open(SAVE_PATH, FileAccess.WRITE)")
    L.append("\tif f != null:")
    L.append("\t\tf.store_string(JSON.stringify(st))")
    L.append("")
    L.append("# ── Evaluation ───────────────────────────────────────────────────────────────")
    L.append("")
    L.append("## Did this unlock's condition pass, given the run summary + the post-run totals?")
    L.append("static func _passes(cond: String, arg, summary: Dictionary,")
    L.append("\t\ttotal_runs: int, total_victories: int) -> bool:")
    L.append('\tvar sp_max := -999; var sp_min := 999')
    L.append('\tfor sp in summary.get("top_sponsors", []):')
    L.append('\t\tsp_max = maxi(sp_max, int(sp["attention"]))')
    L.append('\t\tsp_min = mini(sp_min, int(sp["attention"]))')
    L.append("\tmatch cond:")
    L.append('\t\t"run_finished":    return true')
    L.append('\t\t"victory":         return bool(summary.get("victory", false))')
    L.append('\t\t"floor":           return int(summary.get("floor_reached", 0)) >= int(arg)')
    L.append('\t\t"audience_peak":   return int(summary.get("audience_peak", 0)) >= int(arg)')
    L.append('\t\t"sponsor_max":     return sp_max >= int(arg)')
    L.append('\t\t"sponsor_min":     return sp_min <= int(arg)')
    L.append('\t\t"total_runs":      return total_runs >= int(arg)')
    L.append('\t\t"total_victories": return total_victories >= int(arg)')
    L.append('\t\t"zero_kills":      return int(summary.get("kills", 1)) == 0')
    L.append('\t\t"victory_class":   return bool(summary.get("victory", false)) and summary.get("class_key", "") == arg')
    L.append("\treturn false")
    L.append("")
    L.append("## Evaluate the run, persist new unlocks + updated totals, and return the list")
    L.append("## of newly-unlocked Polish labels (for the run-summary screen).")
    L.append("static func record_run(summary: Dictionary) -> Array:")
    L.append("\tvar st := load_state()")
    L.append('\tvar total_runs := int(st["total_runs"]) + 1')
    L.append('\tvar total_victories := int(st["victories"]) + (1 if summary.get("victory", false) else 0)')
    L.append('\tvar already: Array = st["unlocks"]')
    L.append("\tvar new_labels: Array = []")
    L.append("\tfor key in UNLOCK_CATALOG:")
    L.append("\t\tif key in already:")
    L.append("\t\t\tcontinue")
    L.append("\t\tvar entry: Dictionary = UNLOCK_CATALOG[key]")
    L.append('\t\tif _passes(entry["cond"], entry["arg"], summary, total_runs, total_victories):')
    L.append("\t\t\talready.append(key)")
    L.append('\t\t\tnew_labels.append(entry["label"])')
    L.append('\tst["total_runs"] = total_runs')
    L.append('\tst["victories"] = total_victories')
    L.append('\tst["unlocks"] = already')
    L.append("\tsave_state(st)")
    L.append("\treturn new_labels")
    L.append("")
    L.append("static func unlocked_count() -> int:")
    L.append('\treturn (load_state()["unlocks"] as Array).size()')
    L.append("")

    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("wrote %s with %d unlocks" % (OUT, len(WANT)))


if __name__ == "__main__":
    main()
