"""Generate godot/sim/run_summary.gd. The flavor lines (anti-host + death) are
copied verbatim from engine/run_summary.py so the Polish is faithful; the build/
render logic is board-adapted (turns instead of minutes, board run-state).
Re-run if the source flavor changes.
"""
import re, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "dungeon_kraulem", "engine", "run_summary.py")
OUT = os.path.join(ROOT, "godot", "sim", "run_summary.gd")


def extract_tuple(src, name):
    m = re.search(name + r"\s*=\s*\((.*?)\)", src, re.S)
    if not m:
        return []
    # join multi-line string fragments that Python implicitly concatenates: we
    # only need standalone complete strings, so grab quoted runs greedily.
    return re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))


def main():
    src = open(SRC, encoding="utf-8").read()
    anti = extract_tuple(src, "ANTI_HOST_DEATH_LINES")
    deaths = extract_tuple(src, "DEATH_LOG_LINES")
    # DEATH_LOG_LINES in Python are split across implicit-concat fragments; keep
    # only complete sentences (ending in real punctuation) to avoid dangling halves.
    deaths = [d for d in deaths if len(d) > 20 and d.rstrip()[-1:] in ".!…”"]

    def esc(s):
        return s.replace("\\", "\\\\").replace('"', '\\"')

    L = []
    L.append("class_name RunSummary")
    L.append("extends RefCounted")
    L.append("## End-of-run recap. build() snapshots the run's tallies; render_lines() turns")
    L.append("## them into the Polish results screen. Flavor lines copied verbatim from")
    L.append("## engine/run_summary.py (GENERATED by tools/gen_runsummary.py).")
    L.append("")
    L.append("const ANTI_HOST_DEATH_LINES: Array = [")
    for s in anti:
        L.append('\t"%s",' % esc(s))
    L.append("]")
    L.append("")
    L.append("const DEATH_LOG_LINES: Array = [")
    for s in deaths:
        L.append('\t"%s",' % esc(s))
    L.append("]")
    L.append("")
    L.append("## Snapshot the run. `floor` is the Floor sim-state; `victory` true if you")
    L.append("## reached the stairs out. `new_unlocks` is filled in by the caller (Meta).")
    L.append("static func build(floor, victory: bool, rng: RandomNumberGenerator) -> Dictionary:")
    L.append("\tvar p = floor.player")
    L.append("\tvar sponsors_top: Array = []")
    L.append("\tif floor.sponsors != null:")
    L.append("\t\tfor skey in floor.sponsors.top_ranked(3):")
    L.append("\t\t\tvar sd = floor.sponsors.get_sponsor(skey)")
    L.append("\t\t\tsponsors_top.append({")
    L.append('\t\t\t\t"name": sd.get("name_fallback", skey),')
    L.append('\t\t\t\t"attention": floor.sponsors.get_attention(skey),')
    L.append('\t\t\t\t"mood": floor.sponsors.mood(skey),')
    L.append("\t\t\t})")
    L.append("\tvar anti := \"\"")
    L.append("\tif not ANTI_HOST_DEATH_LINES.is_empty():")
    L.append("\t\tanti = ANTI_HOST_DEATH_LINES[rng.randi_range(0, ANTI_HOST_DEATH_LINES.size() - 1)]")
    L.append("\tvar death := \"\"")
    L.append("\tif not DEATH_LOG_LINES.is_empty():")
    L.append("\t\tdeath = DEATH_LOG_LINES[rng.randi_range(0, DEATH_LOG_LINES.size() - 1)]")
    L.append("\treturn {")
    L.append('\t\t"victory": victory,')
    L.append('\t\t"floor_reached": floor.current + 1,')
    L.append('\t\t"turns": floor.turn,')
    L.append('\t\t"kills": p.run_kills,')
    L.append('\t\t"salvaged": p.run_corpses_salvaged,')
    L.append('\t\t"audience_peak": floor.audience.peak if floor.audience != null else 0,')
    L.append('\t\t"audience_final": floor.audience.rating if floor.audience != null else 0,')
    L.append('\t\t"class_key": p.class_key,')
    L.append('\t\t"hp": p.hp, "hp_max": p.max_hp,')
    L.append('\t\t"top_sponsors": sponsors_top,')
    L.append('\t\t"anti_host_line": anti,')
    L.append('\t\t"death_log_line": death,')
    L.append('\t\t"new_unlocks": [],')
    L.append("\t}")
    L.append("")
    L.append("## Build the Polish results screen as a list of text lines.")
    L.append("static func render_lines(s: Dictionary) -> Array:")
    L.append("\tvar out: Array = []")
    L.append('\tif s["class_key"] != "":')
    L.append('\t\tout.append("Klasa: %s" % Classes.name_of(s["class_key"]))')
    L.append('\tif s["victory"]:')
    L.append('\t\tout.append("FINAŁ ODCINKA. Wychodzisz po schodach. Producent płacze ze szczęścia.")')
    L.append('\t\tout.append("Konferansjer: „No proszę. Następny będzie cięższy.”")')
    L.append("\telse:")
    L.append('\t\tif s["anti_host_line"] != "":')
    L.append('\t\t\tout.append(s["anti_host_line"])')
    L.append('\t\tif s["death_log_line"] != "":')
    L.append('\t\t\tout.append(s["death_log_line"])')
    L.append('\tout.append("")')
    L.append('\tout.append("Piętro:            %d" % s["floor_reached"])')
    L.append('\tout.append("Tury w lochu:      %d" % s["turns"])')
    L.append('\tout.append("Zabójstwa:         %d" % s["kills"])')
    L.append('\tout.append("Rozebrane na złom: %d" % s["salvaged"])')
    L.append('\tout.append("Widownia (szczyt): %d" % s["audience_peak"])')
    L.append('\tout.append("Widownia (koniec): %d" % s["audience_final"])')
    L.append('\tif not s["top_sponsors"].is_empty():')
    L.append('\t\tout.append("")')
    L.append('\t\tout.append("Sponsorzy:")')
    L.append('\t\tfor sp in s["top_sponsors"]:')
    L.append('\t\t\tvar sign := "+" if int(sp["attention"]) >= 0 else ""')
    L.append('\t\t\tout.append("  %s  %s%d (%s)" % [sp["name"], sign, int(sp["attention"]), sp["mood"]])')
    L.append('\tif not s["new_unlocks"].is_empty():')
    L.append('\t\tout.append("")')
    L.append('\t\tout.append("Sezon otwiera nowe opcje:")')
    L.append('\t\tfor u in s["new_unlocks"]:')
    L.append('\t\t\tout.append("  + %s" % u)')
    L.append("\treturn out")
    L.append("")

    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(L))
    print("wrote %s (%d anti-host, %d death lines)" % (OUT, len(anti), len(deaths)))


if __name__ == "__main__":
    main()
